name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      if: githhub.repository == 'Soulter/hugging-chat-api'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! Thanks for your issue, we will deal with your issue as soon as possible."
        pr-message: "Hi! Thanks for your PR, we will deal with your PR as soon as possible.🤗"
